### ISSUE TITLE
Keeping files separate

### ISSUE THREAD

**Issue by mcrossler** [bookbonobo/libby-download-extension#1]
Love the extension! Can there a way to be able to choose if we want the file combined or not? My audiobook player doesn't always remember where it last stopped and finding where I left off in a 12-hour file can be exhausting. I'd prefer to have the 10 smaller individual files vs. one large file. I'm wondering if there can be a checkbox prior to downloading where we can choose to keep just the individual files or have the extension combine them all into one large file. Thanks!!!

**Comment by bookbonobo** [comment]
Thanks for the feedback! One way to solve that is to use something like https://github.com/yermak/AudioBookConverter and convert to an m4b file which does support tracking your position. But - a checkbox sounded like a great idea, so I added that as well (you lose chapter info, but that's ok for a lot of folks). The 0.3.0 release is pending Mozilla review, but it should be getting pushed out in the next day or so.
