### ISSUE TITLE
TypeError: o is undefined

### ISSUE THREAD

**Issue by costerhout14** [bookbonobo/libby-download-extension#161]
After working perfectly yesterday, now returns a "TypeError: o is undefined." for multiple books.

**Comment by dumplingbandit** [comment]
I'm using this for the first time and am running into "TypeError: o is undefined" for multiple books as well. Tried refreshing several times. I disabled uBlock, Privacy Badger, and Enhanced Tracking Protection. Unfortunately, no dice.

**Comment by ahxxm** [comment]
I think they changed how the web player parses titleMeta and spine information, [code pointer](https://github.com/bookbonobo/libby-download-extension/blob/main/src/background.ts#L114), at least for the book I inspected that raises "TypeError: o is undefined" error

Response from openbook.json is like `{"book":"some-md5-here?","code":"N001","path":"/_d/openbook.json"}`, and the code expects all title meta from this URL

However, now meta data is hide in HTML of `https://dewey-{rsp.md5}.listen.libbyshelf.com/{rsp.message}`, and the HTML sets all fields into `windows.bData`(which window?)

**Comment by NotKoalafied** [comment]
Crossposting a fix that we have found for the Libby Audiobook Exporter made by Hou Tianze. I have tried this with this add-on and had luck with it, so maybe it'll help you too.

[Uncaught TypeError: Cannot read properties of undefined - FIX](https://github.com/houtianze/libby-audiobook-exporter-browser-extension/issues/12#issuecomment-2054137815)
