### ISSUE TITLE
Libby Downloader hangs: continuation of May 13 issue

### ISSUE THREAD

**Issue by mjpking** [bookbonobo/libby-download-extension#18]
FireFox 91.11.0esr (64-bit)
Debian 5.10.0-13-amd64

Version 0.4.0

![Screenshot_2023-06-24_13-58-45](https://github.com/bookbonobo/libby-download-extension/assets/133550431/1415aa48-fb89-4df1-9160-996b40a97f48)

**Comment by bookbonobo** [comment]
That is indeed a different issue, thanks for reopening. Is there any way you could test on a more recent version of Firefox? I know it’s an ESR build, but the 91 release was 2 years ago (we’re up to 114 now). I’ll see about reproducing locally with that build in the meantime.

**Comment by bookbonobo** [comment]
Confirmed this extension is incompatible with that version of Firefox. Confirmed working on 102 ESR build that ships with Debian Bullseye. Assuming you're running Buster still, my recommendation would be to upgrade to Bullseye to get a more current build (it's EOL in 2 months anyway).
