### ISSUE TITLE
Issue in cue sheet keeps mp3splt from recognizing book title

### ISSUE THREAD

**Issue by kmacinnis** [bookbonobo/libby-download-extension#2]
Cue sheets right now start with Title "{book title}"
This need to be TITLE "{book title}" for certain utilities (like mp3splt) to recognize the book title.
Pull request coming

**Comment by bookbonobo** [comment]
Thanks for your contribution! PR was merged and this change will be available in the 0.3.0 release (pending Mozilla approval now)
