### ISSUE TITLE
Chapters not creating precisely

### ISSUE THREAD

**Issue by pmorgan111** [bookbonobo/libby-download-extension#47]
This is a small problem, but it would be nice if you could figure out how to resolve it. I have been downloading my books using the "parse" methodology which outputs one large .mp3 file and one .cue file. I have used various software apps to separate the large .mp3 file, creating chapters. The problem is I find that sometimes the start of a new chapter includes a few seconds of the previous chapter. I have tried 3 software apps to create chapters and they all give the same results. For instance, in the book "The Death of Mrs. Westaway" by Ruth Ware, the chapters get out of sync starting at track 31 (this is the book's chapter 28). So, at the beginning of track 31 you hear a few seconds of the end of track 30. This situation continues for the rest of the book, at the beginning of each chapter you hear a few seconds of the end of the previous chapter. At first I thought that maybe the software I was using to create tracks (chapters) was faulty but inasmuch as they all created tracks of the same length, I am wondering if data in the .cue file might not be 100% accurate. Anyway, please let me know your thoughts and if there is anything I could do to help. I did try the Libby apps (Android and PC) and using those apps I am able to navigate chapters without any issues.

**Comment by bookbonobo** [comment]
After looking at it - what's happening here is that there's a cumulative effect of a small inaccuracy (hundreds of milliseconds) in the duration returned by the mp3 files themselves. It's actually very slightly off starting all the way back at Chapter 6, just not enough to be noticeable. By the time you get to 28 it's enough of a difference that the silence between chapters doesn't hide it anymore. 

Bad news is that the only fix for this is to decode the audio stream yourself and use that to calculate the duration of the file. Good news is that when you do that every chapter is accurate within a second. I'll cut a release shortly that includes an option for "Precise Chapters" which does the more accurate duration calculation but is much slower (~15 seconds vs ~3 and a half minutes for "The Death of Mrs. Westaway").

**Comment by pmorgan111** [comment]
Thanks for the explanation. I really appreciate it. It would be great if you could offer users the option to create more precise chapter delineation. Everyone's mileage concerning chapters is probably quite different. Some people don't care about chapters, others do. And it depends what kind of player app you're using. On Android I've used Sirin. It can delineate chapters straight from your conversion extension as I guess it interprets the .cue file created in the extension. If you use Sirin the book will play smoothly from start to finish as it uses only 1 .mp3 file and therefore no need to skip to the next file to hear the next chapter.  An app like Smart AudioBook cannot do that but can offer chapter support if the large .mp3 is broken into smaller chapter files. However, if you want to use Smart AudioBook for chapter navigation and the chapter duration is not 100% calculated correctly you may hear a slight hesitation in the recording when the app skips from one chapter to another. Anyway, that's my experience. You can tell I would opt for longer conversion time if I could be assured of precise chapter duration. I am sure many others would prefer faster conversion time. I'll keep looking to see when this becomes available. Thanks so much!

**Comment by bookbonobo** [comment]
Resolved in [0.5.0](https://github.com/bookbonobo/libby-download-extension/releases/tag/0.5.0)

**Comment by pmorgan111** [comment]
This looks great! The increased time to download doesn't bother me a bit, especially when I know the chapters will be parsed exactly as parsed in Libby. Many thanks.
