### ISSUE TITLE
Extension Hangs

### ISSUE THREAD

**Issue by tramzee** [bookbonobo/libby-download-extension#5]
(I am not sure if this is the correct place for this issue. Apologies if not.)

I have successfully used the add-on in the past (a little over a month ago). Today, when I tried to download an audiobook the add-on just hangs with this:

![image](https://user-images.githubusercontent.com/16690/226146571-676e5df7-2bd4-4759-9a06-68bb5ebb29a0.png)

I have tried several books with the same behavior. I have toggled the "Parse Chapters" on and off with the same behavior. I have tried deleting than re-downloading with the same behavior.

Note: this is on Windows 10 Home OS

**Comment by maxwallgren** [comment]
Same problem with Win 10 Pro and Ubuntu 22.04 (Snap). Worked a week ago, but hangs now.

**Comment by Martin-Bog** [comment]
Same Problem with Windows 11 & Firefox. Worked fine 4 days ago without the chapter option. I think it's the update.

**Comment by Prajna-Karuna** [comment]
Same here. I've tried all the tricks I could think of and still nothing.

**Comment by bookbonobo** [comment]
I’m seeing the same behavior now as well - but wasn’t when I implemented the skip parsing check box. It looks like it’s hanging waiting for some state to come through. My guess is that something changed on their backend. I should have time to look at it this week

**Comment by bookbonobo** [comment]
@Prajna-Karuna @tramzee could you try again? I went to look at it and the currently released version is working for me again.

**Comment by tramzee** [comment]
@bookbonobo, yes it is working for me again! Thank you for checking on this

**Comment by maxwallgren** [comment]
Works now!
