### ISSUE TITLE
Truncated download of audio

### ISSUE THREAD

**Issue by sherip99** [bookbonobo/libby-download-extension#7]
I tried downloading a collection of books (one title) that lacked chapter markers of each book. Libby downloader got each "book" as a track-chapter (ok) but unfortunately the first title was exceptionally long, and the download of that track ended prematurely ie only about half of its audio got downloaded. The other two books (which followed that one) did download completely. So the truncated portion was in the middle of the overall content.

**Comment by bookbonobo** [comment]
Probably the same underlying issue as #9. I'm going to close this, but feel free to open a new issue if your problem persists.

**Comment by universvm** [comment]
Hi @bookbonobo , I seem to have the same problem with the latest version from the Firefox Add-On Store. 

<img width="440" alt="Screenshot 2023-07-16 at 07 42 01" src="https://github.com/bookbonobo/libby-download-extension/assets/17524568/9b923dc9-55a4-49ea-ae53-e8ab1992e262">

When I click on OFF for Parse Chapters, the download proceeds. However some parts are missing:

<img width="441" alt="Screenshot 2023-07-16 at 07 47 11" src="https://github.com/bookbonobo/libby-download-extension/assets/17524568/31b08481-4d63-413d-9846-1ff8f388dab0">
